variable "rgname" {}
variable "location" {}
variable "sqlpassword" {}
variable "sqluser" {}
variable "sqlsrvrname" {}
variable "ehname" {}
variable "ehnsname" {}
variable "storagename" {}
variable "acrname" {}
